# Generated by Django 4.2.30 on 2026-08-19 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Chief Jerry's 80th Birthday", max_length=200
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("venue_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("dress_code", models.CharField(max_length=100)),
                ("rsvp_deadline", models.DateField()),
                ("about_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MealOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_options",
                        to="event_invitations_app.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "attending",
                    models.CharField(
                        choices=[
                            ("YES", "Yes, I will be attending"),
                            ("NO", "No, I will not be attending"),
                        ],
                        default="YES",
                        max_length=3,
                    ),
                ),
                (
                    "guest_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("dietary_requirements", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="event_invitations_app.event",
                    ),
                ),
                (
                    "primary_meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_rsvps",
                        to="event_invitations_app.mealoption",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="ProgramItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "icon_name",
                    models.CharField(
                        help_text="FontAwesome or SVG icon name", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="event_invitations_app.event",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("about", "About Dad"), ("memory", "80 Years")],
                        max_length=50,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="event_invitations_app.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "meal_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest_meals",
                        to="event_invitations_app.mealoption",
                    ),
                ),
                (
                    "rsvp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_guests",
                        to="event_invitations_app.rsvp",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(fields=["email"], name="event_invit_email_d54036_idx"),
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(
                fields=["created_at"], name="event_invit_created_a88592_idx"
            ),
        ),
    ]
