# Generated by Django 4.2.30 on 2026-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_invitations_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="programitem", name="event",),
        migrations.RemoveField(model_name="additionalguest", name="meal_option",),
        migrations.RemoveField(model_name="rsvp", name="primary_meal",),
        migrations.AlterField(
            model_name="rsvp",
            name="dietary_requirements",
            field=models.TextField(
                blank=True,
                help_text="Dietary restrictions or allergies for primary guest or party",
            ),
        ),
        migrations.DeleteModel(name="MealOption",),
        migrations.DeleteModel(name="ProgramItem",),
    ]
