# Generated by Django 4.2.30 on 2026-08-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_invitations_app", "0002_remove_programitem_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="about_text",),
        migrations.RemoveField(model_name="event", name="address",),
        migrations.RemoveField(model_name="event", name="dress_code",),
        migrations.AddField(
            model_name="event",
            name="invitation_passcode",
            field=models.CharField(
                default="JERRY80",
                help_text="Shared passcode required for guests to submit an RSVP",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                default="Chief Jerry's 80th Birthday Celebration", max_length=200
            ),
        ),
    ]
