# Generated by Django 4.2.30 on 2026-08-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "event_invitations_app",
            "0003_remove_event_about_text_remove_event_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("Chief", "Chief"),
                    ("Dr", "Dr"),
                    ("Eng", "Eng"),
                    ("Esq.", "Esq."),
                    ("Mr & Mrs.", "Mr & Mrs."),
                    ("Jr.", "Jr."),
                    ("Sr.", "Sr."),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
