# Generated by Django 4.2.30 on 2026-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_invitations_app", "0004_rsvp_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsvp",
            name="guest_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("Chief", "Chief"),
                    ("Rev.", "Rev."),
                    ("Dr.", "Dr."),
                    ("Eng.", "Eng."),
                    ("Esq.", "Esq."),
                    ("Mr & Mrs", "Mr & Mrs"),
                    ("Jr.", "Jr."),
                    ("Sr.", "Sr."),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
