# Generated by Django 4.2.30 on 2026-08-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_invitations_app", "0005_alter_rsvp_guest_count_alter_rsvp_suffix"),
    ]

    operations = [
        migrations.RemoveField(model_name="galleryimage", name="caption",),
        migrations.AddField(
            model_name="galleryimage",
            name="description",
            field=models.CharField(
                blank=True, help_text="Image description", max_length=255, null=True
            ),
        ),
    ]
