# Generated by Django 4.2.30 on 2026-08-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invitations_app', '0006_remove_galleryimage_caption_galleryimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='crop_position',
            field=models.CharField(choices=[('center 15%', 'Top / Face Focus (Recommended for Portraits)'), ('center center', 'Center (Default)'), ('center top', 'Very Top'), ('center bottom', 'Bottom')], default='center 15%', help_text='Controls how the photo is framed in the gallery card.', max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(blank=True, help_text='Image description (max 200 chars)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='birthday_gallery/'),
        ),
    ]
