# Generated by Django 4.2.30 on 2026-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invitations_app', '0007_galleryimage_crop_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='fit_mode',
            field=models.CharField(choices=[('cover', 'Crop & Fill Card (Uses Focus Alignment)'), ('contain', 'Fit Entire Photo (No Cutting Off / Letterboxed)')], default='cover', help_text="Select 'Fit Entire Photo' if important parts keep getting cut off.", max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='crop_position',
            field=models.CharField(choices=[('center 15%', 'Top / Face Focus (Recommended for Portraits)'), ('center top', 'Very Top Edge'), ('center center', 'Center / Middle'), ('center bottom', 'Very Bottom Edge'), ('left center', 'Far Left Focus'), ('right center', 'Far Right Focus')], default='center 15%', help_text='Controls how the photo is framed when cropped.', max_length=20),
        ),
    ]
