# Generated by Django 4.2.30 on 2026-08-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invitations_app', '0008_galleryimage_fit_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='crop_position',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='fit_mode',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('about', 'About Dad'), ('memory', '80 Years')], default='about', max_length=50),
        ),
    ]
