# Generated by Django 4.2.30 on 2026-08-29 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invitations_app', '0010_alter_rsvp_guest_count_alter_rsvp_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Mr.', 'Mr.'), ('Mr & Mrs', 'Mr & Mrs'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Nze', 'Nze'), ('Chief', 'Chief'), ('Rev.', 'Rev.'), ('Dr.', 'Dr.'), ('Eng.', 'Eng.'), ('Esq.', 'Esq.'), ('Jr.', 'Jr.'), ('Sr.', 'Sr.')], default='', max_length=20),
        ),
    ]
