# Generated by Django 4.2.30 on 2026-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invitations_app', '0011_alter_rsvp_guest_count_alter_rsvp_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_stream_link',
            field=models.URLField(blank=True, help_text='Optional link for virtual attendance (Zoom, YouTube, Google Meet, etc.)', max_length=500, null=True),
        ),
    ]
