# Generated by Django 4.2.30 on 2026-09-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invitations_app', '0012_event_live_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_access_code',
            field=models.CharField(default='JERRYLIVE', help_text='Code required to access the live event and livestream', max_length=50),
        ),
    ]
